---
title: "PROJET D’ANALYSE DE DONNEES"
date: "3MIC - 2024-2025"
output:
  pdf_document:
    toc: true
    toc_depth: '4'
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    number_sections: true
---

```{css,echo=F}
.badCode {
background-color: #C9DDE4;
}

.corrO { background-color: rgb(255,238,237); }
.corrS { background-color: pink; color: black; border: 1px solid red; }
```


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               class.source="badCode")
opts_knit$set(width=75)
```

```{r,echo=F, error=F,warning=F}
library(corrplot)
library(ggplot2)
library(gridExtra)
library(forcats)
library(reshape2)
library(BioStatR)
```

Ce projet a été réalisé par un groupe de 3 étudiants.

```{r}
data <- read.table("DataProjet3MIC-2425.txt",header=TRUE,sep=";")

head(data)

dim(data)

nrow(data)

ncol(data)

attributes(data)

str(data)

summary(data)
```


# Analyse uni-dimensionnelle et bi-dimensionnelle du jeu de données

## Variables qualitatives

```{r}
levels(data$Type)

summary(data)

EffType = as.
```